name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image for user app
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.user
        push: true
        tags: arinsingh/ezpay:latest
        build-args: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}

    - name: Build and Push Docker image for bank-webhook app
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.bank-webhook
        push: true
        tags: arinsingh/bank-webhook:latest
        build-args: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}

    - name: Verify Pushed Images
      run: |
        docker pull arinsingh/ezpay:latest
        docker pull arinsingh/bank-webhook:latest